name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Linting
        uses: docker://texthtml/phpcs
        with:
          args: phpcs --standard=PSR2 Classes
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: GIT checkout 
        uses: actions/checkout@v1
      - name: Composer install all dependencies
        uses: docker://composer
        with:
          args: install
